version: "3.8"

services:
  rabbitmq:
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      retries: 20

  mssql:
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PBeycL18545#f", "-Q", "IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'keycloak-dev') BEGIN CREATE DATABASE [keycloak-dev]; END"]
      interval: 1s
      retries: 20

  keycloak:
    depends_on:
      mssql:
        condition: service_healthy
        restart: true

  cqrs-api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_ConnectionStrings__DefaultConnection=Server=mssql;Initial Catalog=goal-dev;Persist Security Info=False;User ID=sa;Password=BeycL18545#f;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=True;MultiSubnetFailover=True;Connection Timeout=30;
        - ASPNETCORE_ConnectionStrings__Seq=http://seq:5341
        - ASPNETCORE_ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672
        - ASPNETCORE_URLS=https://+;http://+
        - ASPNETCORE_HTTPS_PORT=4431
        - ASPNETCORE_RavenSettings__Urls=http://ravendb:8080
        - ASPNETCORE_RavenSettings__DatabaseName=Sample
        - ASPNETCORE_RavenSettings__CertFilePath=
        - ASPNETCORE_RavenSettings__CertPassword=
        - ASPNETCORE_Auth__Authority=http://kubernetes.docker.internal:8001
        - ASPNETCORE_Auth__Scopes=openid profile goal.read goal.write manage
        - ASPNETCORE_Auth__ClientId=goal.web
        - ASPNETCORE_Auth__ClientSecret=secret
        - ASPNETCORE_Cors__Origins=https://localhost:4432;http://localhost:8002;http://localhost:4200
        - ASPNETCORE_Kestrel__Certificates__Default__Password=fd7ccf84-1ff8-4817-9ecd-f0a2047ea262
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/Development.pfx
    volumes:
        - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
        - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
        - ${USERPROFILE}\.aspnet\DataProtection-Keys:/root/.aspnet/DataProtection-Keys/
    depends_on:
      mssql:
        condition: service_healthy
        restart: true
      ravendb:
        condition: service_healthy
        restart: true
      rabbitmq:
        condition: service_healthy
        restart: true

  cqrs-worker:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_ConnectionStrings__DefaultConnection=Server=mssql;Initial Catalog=goal-dev;Persist Security Info=False;User ID=sa;Password=BeycL18545#f;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=True;MultiSubnetFailover=True;Connection Timeout=30;
        - ASPNETCORE_ConnectionStrings__Seq=http://seq:5341
        - ASPNETCORE_ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672
        - ASPNETCORE_RavenSettings__Urls=http://ravendb:8080
        - ASPNETCORE_RavenSettings__DatabaseName=Sample
        - ASPNETCORE_RavenSettings__CertFilePath=
        - ASPNETCORE_RavenSettings__CertPassword=
        - ASPNETCORE_Cors__Origins=https://localhost:4432;http://localhost:8002;http://localhost:4200
        - ASPNETCORE_Kestrel__Certificates__Default__Password=fd7ccf84-1ff8-4817-9ecd-f0a2047ea262
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/Development.pfx
    volumes:
        - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
        - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
        - ${USERPROFILE}\.aspnet\DataProtection-Keys:/root/.aspnet/DataProtection-Keys/
    depends_on:
      mssql:
        condition: service_healthy
        restart: true
      ravendb:
        condition: service_healthy
        restart: true
      rabbitmq:
        condition: service_healthy
        restart: true
