version: "3.8"

services:

  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_ConnectionStrings__DefaultConnection=Server=mssql;Initial Catalog=goal-dev;Persist Security Info=False;User ID=sa;Password=BeycL18545#f;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=True;MultiSubnetFailover=True;Connection Timeout=30;
      - ASPNETCORE_ConnectionStrings__Seq=http://seq:5341
      - ASPNETCORE_SigninCredentials__Path=/root/.aspnet/https/ritter.starter.co.pfx
      - ASPNETCORE_SigninCredentials__Password=16a56c6b-bc2f-4eb0-841a-f943d811ec42
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=4431
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/Development.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=fd7ccf84-1ff8-4817-9ecd-f0a2047ea262
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
      - ${USERPROFILE}\.aspnet\DataProtection-Keys:/root/.aspnet/DataProtection-Keys/

  cqrs-api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_ConnectionStrings__DefaultConnection=Server=mssql;Initial Catalog=goal-dev;Persist Security Info=False;User ID=sa;Password=BeycL18545#f;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=True;MultiSubnetFailover=True;Connection Timeout=30;
        - ASPNETCORE_ConnectionStrings__Seq=http://seq:5341
        - ASPNETCORE_ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672
        - ASPNETCORE_URLS=https://+;http://+
        - ASPNETCORE_HTTPS_PORT=4431
        - ASPNETCORE_RavenSettings__Urls=http://ravendb:8080
        - ASPNETCORE_RavenSettings__DatabaseName=Sample
        - ASPNETCORE_RavenSettings__CertFilePath=
        - ASPNETCORE_RavenSettings__CertPassword=
        - ASPNETCORE_Auth__Authority=http://kubernetes.docker.internal:8001
        - ASPNETCORE_Auth__Scopes=openid profile goal.read goal.write manage
        - ASPNETCORE_Auth__ClientId=goal.web
        - ASPNETCORE_Auth__ClientSecret=secret
        - ASPNETCORE_Cors__Origins=https://localhost:4432;http://localhost:8002;http://localhost:4200
        - ASPNETCORE_Kestrel__Certificates__Default__Password=fd7ccf84-1ff8-4817-9ecd-f0a2047ea262
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/Development.pfx
    volumes:
        - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
        - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
        - ${USERPROFILE}\.aspnet\DataProtection-Keys:/root/.aspnet/DataProtection-Keys/

  cqrs-worker:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_ConnectionStrings__DefaultConnection=Server=mssql;Initial Catalog=goal-dev;Persist Security Info=False;User ID=sa;Password=BeycL18545#f;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=True;MultiSubnetFailover=True;Connection Timeout=30;
        - ASPNETCORE_ConnectionStrings__Seq=http://seq:5341
        - ASPNETCORE_ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672
        - ASPNETCORE_RavenSettings__Urls=http://ravendb:8080
        - ASPNETCORE_RavenSettings__DatabaseName=Sample
        - ASPNETCORE_RavenSettings__CertFilePath=
        - ASPNETCORE_RavenSettings__CertPassword=
        - ASPNETCORE_Cors__Origins=https://localhost:4432;http://localhost:8002;http://localhost:4200
        - ASPNETCORE_Kestrel__Certificates__Default__Password=fd7ccf84-1ff8-4817-9ecd-f0a2047ea262
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/Development.pfx
    volumes:
        - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
        - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
        - ${USERPROFILE}\.aspnet\DataProtection-Keys:/root/.aspnet/DataProtection-Keys/
